/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as AuthFinishRouteImport } from './routes/auth/finish'
import { Route as ProtectedNewWishRouteRouteImport } from './routes/_protected/new-wish/route'
import { Route as ProtectedNewWishIndexRouteImport } from './routes/_protected/new-wish/index'
import { Route as ProtectedProfileUserIdRouteImport } from './routes/_protected/profile/$userId'
import { Route as ProtectedNewWishPreviewRouteImport } from './routes/_protected/new-wish/preview'
import { Route as ProtectedsearchSearchRouteImport } from './routes/_protected/(search)/search'
import { Route as ProtectednotificationsNotificationsRouteImport } from './routes/_protected/(notifications)/notifications'
import { Route as ProtectedhomeHomeRouteImport } from './routes/_protected/(home)/home'
import { Route as ProtectedgiftsGiftsRouteImport } from './routes/_protected/(gifts)/gifts'
import { Route as ProtectedProfileUserIdIndexRouteImport } from './routes/_protected/profile/$userId/index'
import { Route as ProtectedProfileUserIdFollowingIndexRouteImport } from './routes/_protected/profile/$userId/following/index'
import { Route as ProtectedProfileUserIdFollowersIndexRouteImport } from './routes/_protected/profile/$userId/followers/index'
import { Route as ProtectedProfileUserIdFeedIndexRouteImport } from './routes/_protected/profile/$userId/feed/index'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFinishRoute = AuthFinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedNewWishRouteRoute = ProtectedNewWishRouteRouteImport.update({
  id: '/new-wish',
  path: '/new-wish',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedNewWishIndexRoute = ProtectedNewWishIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedNewWishRouteRoute,
} as any)
const ProtectedProfileUserIdRoute = ProtectedProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedNewWishPreviewRoute = ProtectedNewWishPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => ProtectedNewWishRouteRoute,
} as any)
const ProtectedsearchSearchRoute = ProtectedsearchSearchRouteImport.update({
  id: '/(search)/search',
  path: '/search',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectednotificationsNotificationsRoute =
  ProtectednotificationsNotificationsRouteImport.update({
    id: '/(notifications)/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedhomeHomeRoute = ProtectedhomeHomeRouteImport.update({
  id: '/(home)/home',
  path: '/home',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedgiftsGiftsRoute = ProtectedgiftsGiftsRouteImport.update({
  id: '/(gifts)/gifts',
  path: '/gifts',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedProfileUserIdIndexRoute =
  ProtectedProfileUserIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedProfileUserIdRoute,
  } as any)
const ProtectedProfileUserIdFollowingIndexRoute =
  ProtectedProfileUserIdFollowingIndexRouteImport.update({
    id: '/following/',
    path: '/following/',
    getParentRoute: () => ProtectedProfileUserIdRoute,
  } as any)
const ProtectedProfileUserIdFollowersIndexRoute =
  ProtectedProfileUserIdFollowersIndexRouteImport.update({
    id: '/followers/',
    path: '/followers/',
    getParentRoute: () => ProtectedProfileUserIdRoute,
  } as any)
const ProtectedProfileUserIdFeedIndexRoute =
  ProtectedProfileUserIdFeedIndexRouteImport.update({
    id: '/feed/',
    path: '/feed/',
    getParentRoute: () => ProtectedProfileUserIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/new-wish': typeof ProtectedNewWishRouteRouteWithChildren
  '/auth/finish': typeof AuthFinishRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/': typeof AuthIndexRoute
  '/gifts': typeof ProtectedgiftsGiftsRoute
  '/home': typeof ProtectedhomeHomeRoute
  '/notifications': typeof ProtectednotificationsNotificationsRoute
  '/search': typeof ProtectedsearchSearchRoute
  '/new-wish/preview': typeof ProtectedNewWishPreviewRoute
  '/profile/$userId': typeof ProtectedProfileUserIdRouteWithChildren
  '/new-wish/': typeof ProtectedNewWishIndexRoute
  '/profile/$userId/': typeof ProtectedProfileUserIdIndexRoute
  '/profile/$userId/feed': typeof ProtectedProfileUserIdFeedIndexRoute
  '/profile/$userId/followers': typeof ProtectedProfileUserIdFollowersIndexRoute
  '/profile/$userId/following': typeof ProtectedProfileUserIdFollowingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/finish': typeof AuthFinishRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth': typeof AuthIndexRoute
  '/gifts': typeof ProtectedgiftsGiftsRoute
  '/home': typeof ProtectedhomeHomeRoute
  '/notifications': typeof ProtectednotificationsNotificationsRoute
  '/search': typeof ProtectedsearchSearchRoute
  '/new-wish/preview': typeof ProtectedNewWishPreviewRoute
  '/new-wish': typeof ProtectedNewWishIndexRoute
  '/profile/$userId': typeof ProtectedProfileUserIdIndexRoute
  '/profile/$userId/feed': typeof ProtectedProfileUserIdFeedIndexRoute
  '/profile/$userId/followers': typeof ProtectedProfileUserIdFollowersIndexRoute
  '/profile/$userId/following': typeof ProtectedProfileUserIdFollowingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/_protected/new-wish': typeof ProtectedNewWishRouteRouteWithChildren
  '/auth/finish': typeof AuthFinishRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/(gifts)/gifts': typeof ProtectedgiftsGiftsRoute
  '/_protected/(home)/home': typeof ProtectedhomeHomeRoute
  '/_protected/(notifications)/notifications': typeof ProtectednotificationsNotificationsRoute
  '/_protected/(search)/search': typeof ProtectedsearchSearchRoute
  '/_protected/new-wish/preview': typeof ProtectedNewWishPreviewRoute
  '/_protected/profile/$userId': typeof ProtectedProfileUserIdRouteWithChildren
  '/_protected/new-wish/': typeof ProtectedNewWishIndexRoute
  '/_protected/profile/$userId/': typeof ProtectedProfileUserIdIndexRoute
  '/_protected/profile/$userId/feed/': typeof ProtectedProfileUserIdFeedIndexRoute
  '/_protected/profile/$userId/followers/': typeof ProtectedProfileUserIdFollowersIndexRoute
  '/_protected/profile/$userId/following/': typeof ProtectedProfileUserIdFollowingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/new-wish'
    | '/auth/finish'
    | '/legal/terms'
    | '/auth/'
    | '/gifts'
    | '/home'
    | '/notifications'
    | '/search'
    | '/new-wish/preview'
    | '/profile/$userId'
    | '/new-wish/'
    | '/profile/$userId/'
    | '/profile/$userId/feed'
    | '/profile/$userId/followers'
    | '/profile/$userId/following'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/finish'
    | '/legal/terms'
    | '/auth'
    | '/gifts'
    | '/home'
    | '/notifications'
    | '/search'
    | '/new-wish/preview'
    | '/new-wish'
    | '/profile/$userId'
    | '/profile/$userId/feed'
    | '/profile/$userId/followers'
    | '/profile/$userId/following'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/_protected/new-wish'
    | '/auth/finish'
    | '/legal/terms'
    | '/auth/'
    | '/_protected/(gifts)/gifts'
    | '/_protected/(home)/home'
    | '/_protected/(notifications)/notifications'
    | '/_protected/(search)/search'
    | '/_protected/new-wish/preview'
    | '/_protected/profile/$userId'
    | '/_protected/new-wish/'
    | '/_protected/profile/$userId/'
    | '/_protected/profile/$userId/feed/'
    | '/_protected/profile/$userId/followers/'
    | '/_protected/profile/$userId/following/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/finish': {
      id: '/auth/finish'
      path: '/finish'
      fullPath: '/auth/finish'
      preLoaderRoute: typeof AuthFinishRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/new-wish': {
      id: '/_protected/new-wish'
      path: '/new-wish'
      fullPath: '/new-wish'
      preLoaderRoute: typeof ProtectedNewWishRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/new-wish/': {
      id: '/_protected/new-wish/'
      path: '/'
      fullPath: '/new-wish/'
      preLoaderRoute: typeof ProtectedNewWishIndexRouteImport
      parentRoute: typeof ProtectedNewWishRouteRoute
    }
    '/_protected/profile/$userId': {
      id: '/_protected/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProtectedProfileUserIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/new-wish/preview': {
      id: '/_protected/new-wish/preview'
      path: '/preview'
      fullPath: '/new-wish/preview'
      preLoaderRoute: typeof ProtectedNewWishPreviewRouteImport
      parentRoute: typeof ProtectedNewWishRouteRoute
    }
    '/_protected/(search)/search': {
      id: '/_protected/(search)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedsearchSearchRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(notifications)/notifications': {
      id: '/_protected/(notifications)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectednotificationsNotificationsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(home)/home': {
      id: '/_protected/(home)/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedhomeHomeRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(gifts)/gifts': {
      id: '/_protected/(gifts)/gifts'
      path: '/gifts'
      fullPath: '/gifts'
      preLoaderRoute: typeof ProtectedgiftsGiftsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/profile/$userId/': {
      id: '/_protected/profile/$userId/'
      path: '/'
      fullPath: '/profile/$userId/'
      preLoaderRoute: typeof ProtectedProfileUserIdIndexRouteImport
      parentRoute: typeof ProtectedProfileUserIdRoute
    }
    '/_protected/profile/$userId/following/': {
      id: '/_protected/profile/$userId/following/'
      path: '/following'
      fullPath: '/profile/$userId/following'
      preLoaderRoute: typeof ProtectedProfileUserIdFollowingIndexRouteImport
      parentRoute: typeof ProtectedProfileUserIdRoute
    }
    '/_protected/profile/$userId/followers/': {
      id: '/_protected/profile/$userId/followers/'
      path: '/followers'
      fullPath: '/profile/$userId/followers'
      preLoaderRoute: typeof ProtectedProfileUserIdFollowersIndexRouteImport
      parentRoute: typeof ProtectedProfileUserIdRoute
    }
    '/_protected/profile/$userId/feed/': {
      id: '/_protected/profile/$userId/feed/'
      path: '/feed'
      fullPath: '/profile/$userId/feed'
      preLoaderRoute: typeof ProtectedProfileUserIdFeedIndexRouteImport
      parentRoute: typeof ProtectedProfileUserIdRoute
    }
  }
}

interface ProtectedNewWishRouteRouteChildren {
  ProtectedNewWishPreviewRoute: typeof ProtectedNewWishPreviewRoute
  ProtectedNewWishIndexRoute: typeof ProtectedNewWishIndexRoute
}

const ProtectedNewWishRouteRouteChildren: ProtectedNewWishRouteRouteChildren = {
  ProtectedNewWishPreviewRoute: ProtectedNewWishPreviewRoute,
  ProtectedNewWishIndexRoute: ProtectedNewWishIndexRoute,
}

const ProtectedNewWishRouteRouteWithChildren =
  ProtectedNewWishRouteRoute._addFileChildren(
    ProtectedNewWishRouteRouteChildren,
  )

interface ProtectedProfileUserIdRouteChildren {
  ProtectedProfileUserIdIndexRoute: typeof ProtectedProfileUserIdIndexRoute
  ProtectedProfileUserIdFeedIndexRoute: typeof ProtectedProfileUserIdFeedIndexRoute
  ProtectedProfileUserIdFollowersIndexRoute: typeof ProtectedProfileUserIdFollowersIndexRoute
  ProtectedProfileUserIdFollowingIndexRoute: typeof ProtectedProfileUserIdFollowingIndexRoute
}

const ProtectedProfileUserIdRouteChildren: ProtectedProfileUserIdRouteChildren =
  {
    ProtectedProfileUserIdIndexRoute: ProtectedProfileUserIdIndexRoute,
    ProtectedProfileUserIdFeedIndexRoute: ProtectedProfileUserIdFeedIndexRoute,
    ProtectedProfileUserIdFollowersIndexRoute:
      ProtectedProfileUserIdFollowersIndexRoute,
    ProtectedProfileUserIdFollowingIndexRoute:
      ProtectedProfileUserIdFollowingIndexRoute,
  }

const ProtectedProfileUserIdRouteWithChildren =
  ProtectedProfileUserIdRoute._addFileChildren(
    ProtectedProfileUserIdRouteChildren,
  )

interface ProtectedRouteRouteChildren {
  ProtectedNewWishRouteRoute: typeof ProtectedNewWishRouteRouteWithChildren
  ProtectedgiftsGiftsRoute: typeof ProtectedgiftsGiftsRoute
  ProtectedhomeHomeRoute: typeof ProtectedhomeHomeRoute
  ProtectednotificationsNotificationsRoute: typeof ProtectednotificationsNotificationsRoute
  ProtectedsearchSearchRoute: typeof ProtectedsearchSearchRoute
  ProtectedProfileUserIdRoute: typeof ProtectedProfileUserIdRouteWithChildren
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedNewWishRouteRoute: ProtectedNewWishRouteRouteWithChildren,
  ProtectedgiftsGiftsRoute: ProtectedgiftsGiftsRoute,
  ProtectedhomeHomeRoute: ProtectedhomeHomeRoute,
  ProtectednotificationsNotificationsRoute:
    ProtectednotificationsNotificationsRoute,
  ProtectedsearchSearchRoute: ProtectedsearchSearchRoute,
  ProtectedProfileUserIdRoute: ProtectedProfileUserIdRouteWithChildren,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthFinishRoute: typeof AuthFinishRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthFinishRoute: AuthFinishRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
