/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'
import { Route as AuthFinishRouteImport } from './routes/auth/finish'
import { Route as ProtectedwishlistsWishlistsRouteImport } from './routes/_protected/(wishlists)/wishlists'
import { Route as ProtectedsearchSearchRouteImport } from './routes/_protected/(search)/search'
import { Route as ProtectedprofileProfileRouteImport } from './routes/_protected/(profile)/profile'
import { Route as ProtectednotificationsNotificationsRouteImport } from './routes/_protected/(notifications)/notifications'
import { Route as ProtectedfeedFeedRouteImport } from './routes/_protected/(feed)/feed'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFinishRoute = AuthFinishRouteImport.update({
  id: '/finish',
  path: '/finish',
  getParentRoute: () => AuthRouteRoute,
} as any)
const ProtectedwishlistsWishlistsRoute =
  ProtectedwishlistsWishlistsRouteImport.update({
    id: '/(wishlists)/wishlists',
    path: '/wishlists',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedsearchSearchRoute = ProtectedsearchSearchRouteImport.update({
  id: '/(search)/search',
  path: '/search',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedprofileProfileRoute = ProtectedprofileProfileRouteImport.update({
  id: '/(profile)/profile',
  path: '/profile',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectednotificationsNotificationsRoute =
  ProtectednotificationsNotificationsRouteImport.update({
    id: '/(notifications)/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedfeedFeedRoute = ProtectedfeedFeedRouteImport.update({
  id: '/(feed)/feed',
  path: '/feed',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/finish': typeof AuthFinishRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/': typeof AuthIndexRoute
  '/feed': typeof ProtectedfeedFeedRoute
  '/notifications': typeof ProtectednotificationsNotificationsRoute
  '/profile': typeof ProtectedprofileProfileRoute
  '/search': typeof ProtectedsearchSearchRoute
  '/wishlists': typeof ProtectedwishlistsWishlistsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/finish': typeof AuthFinishRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth': typeof AuthIndexRoute
  '/feed': typeof ProtectedfeedFeedRoute
  '/notifications': typeof ProtectednotificationsNotificationsRoute
  '/profile': typeof ProtectedprofileProfileRoute
  '/search': typeof ProtectedsearchSearchRoute
  '/wishlists': typeof ProtectedwishlistsWishlistsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/auth': typeof AuthRouteRouteWithChildren
  '/auth/finish': typeof AuthFinishRoute
  '/legal/terms': typeof LegalTermsRoute
  '/auth/': typeof AuthIndexRoute
  '/_protected/(feed)/feed': typeof ProtectedfeedFeedRoute
  '/_protected/(notifications)/notifications': typeof ProtectednotificationsNotificationsRoute
  '/_protected/(profile)/profile': typeof ProtectedprofileProfileRoute
  '/_protected/(search)/search': typeof ProtectedsearchSearchRoute
  '/_protected/(wishlists)/wishlists': typeof ProtectedwishlistsWishlistsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auth/finish'
    | '/legal/terms'
    | '/auth/'
    | '/feed'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/wishlists'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/finish'
    | '/legal/terms'
    | '/auth'
    | '/feed'
    | '/notifications'
    | '/profile'
    | '/search'
    | '/wishlists'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/auth'
    | '/auth/finish'
    | '/legal/terms'
    | '/auth/'
    | '/_protected/(feed)/feed'
    | '/_protected/(notifications)/notifications'
    | '/_protected/(profile)/profile'
    | '/_protected/(search)/search'
    | '/_protected/(wishlists)/wishlists'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/finish': {
      id: '/auth/finish'
      path: '/finish'
      fullPath: '/auth/finish'
      preLoaderRoute: typeof AuthFinishRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_protected/(wishlists)/wishlists': {
      id: '/_protected/(wishlists)/wishlists'
      path: '/wishlists'
      fullPath: '/wishlists'
      preLoaderRoute: typeof ProtectedwishlistsWishlistsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(search)/search': {
      id: '/_protected/(search)/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof ProtectedsearchSearchRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(profile)/profile': {
      id: '/_protected/(profile)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedprofileProfileRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(notifications)/notifications': {
      id: '/_protected/(notifications)/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof ProtectednotificationsNotificationsRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/(feed)/feed': {
      id: '/_protected/(feed)/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof ProtectedfeedFeedRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedfeedFeedRoute: typeof ProtectedfeedFeedRoute
  ProtectednotificationsNotificationsRoute: typeof ProtectednotificationsNotificationsRoute
  ProtectedprofileProfileRoute: typeof ProtectedprofileProfileRoute
  ProtectedsearchSearchRoute: typeof ProtectedsearchSearchRoute
  ProtectedwishlistsWishlistsRoute: typeof ProtectedwishlistsWishlistsRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedfeedFeedRoute: ProtectedfeedFeedRoute,
  ProtectednotificationsNotificationsRoute:
    ProtectednotificationsNotificationsRoute,
  ProtectedprofileProfileRoute: ProtectedprofileProfileRoute,
  ProtectedsearchSearchRoute: ProtectedsearchSearchRoute,
  ProtectedwishlistsWishlistsRoute: ProtectedwishlistsWishlistsRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthFinishRoute: typeof AuthFinishRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthFinishRoute: AuthFinishRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
